title: bookTomNYC
baseurl: "/" 
url: "https://tommichael88.github.io/booktomnyc/"

# Build settings
markdown: coderay
theme: jekyll-theme-cayman # Uncomment this if you want to use the Cayman theme
plugins:
  - jekyll-feed

# Custom variables
author:
name: Tom Kongerslev
email: bookTom@icloud.com
#  maintenance_info: "© 2023 Tom Kongerslev. All rights reserved."


# Uncomment and fill in the social links if needed
# social_links:
#   twitter: your_twitter_username
#   github: your_github_username
#   linkedin: your_linkedin_username

# Styling (Custom CSS might be needed for these settings)
style: 
  primary_color: "#4a4a4a" # Dark gray
  accent_color: "#008080"  # Teal
  font_family: "Helvetica, Arial, sans-serif"

# Footer settings
footer:
  copyright: "© 2024 Tom Kongerslev. All rights reserved."
