title: Your Site Name
description: booktomnyc | support documents
baseurl: "/" 
url: "https://tommichael88.github.io/booktomnyc/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Theme customization
minima:
  skin: dark # or you can use 'light'

# Custom variables
author:
  name: Tom Kongerslev
  email: bookTom@icloud.com

# Social links
# social_links:
  
  

# Styling
style:
  primary_color: "#4a4a4a" # Dark gray
  accent_color: "#008080"  # Teal
  font_family: "Helvetica, Arial, sans-serif"

# Footer settings
footer:
  copyright: "© 2023. All rights reserved."

